AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  currency-serverless

  Sample SAM Template for currency-serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CurrencyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: currency/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: An Amazon Lambda function that uses exchange rate API to update currency rates.
      Timeout: 5
      Environment:
        Variables:
          org_db_host_name: org_mysql_container_1
          org_db_username: root
          org_db_password: example